'use strict';
let researchState=null,researchWell=null,templateId=null,researchSequence=0;
const channelNames={gas:'产气',tubing:'油压',casing:'套压',water:'产水',wgr:'水气比',gwr:'气水比'};
const channelUnits={gas:'m³/d',tubing:'MPa',casing:'MPa',water:'m³/d',wgr:'m³/万m³',gwr:'m³/m³'};
const rbadge=t=>`<span class="badge ${/异常|疑似|冲突/.test(t)?'warn':/不足|待/.test(t)?'blue':''}">${esc(t)}</span>`;
const empty=t=>`<div class="empty">${esc(t)}</div>`;
function table(headers,rows){return '<table><thead><tr>'+headers.map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function listText(a){return '<ul class="explain-list">'+a.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>';}

// SVGs are generated from structured numbers; every label is escaped.
function researchChart({title,points,series,xlabel='时间',ylabel='',band=null,id='',dateAxis=false}){
 const W=850,H=285,L=75,R=815,T=45,B=226,valid=points.filter(p=>Number.isFinite(p.x));
 if(!valid.length)return empty('没有满足数据条件的曲线点。');
 const xs=valid.map(p=>p.x),ys=valid.flatMap(p=>[...series.map(s=>p[s.key]),...(band?[p[band[0]],p[band[1]]]:[])]).filter(v=>Number.isFinite(v));
 if(!ys.length)return empty('此参数无有效样本。');
 const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(0,...ys),ymax=Math.max(...ys)*1.08||1;
 const xx=v=>L+(v-xmin)/(xmax-xmin||1)*(R-L),yy=v=>B-(v-ymin)/(ymax-ymin||1)*(B-T);
 let s=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title)}" ${id?'id="'+id+'"':''}><rect width="${W}" height="${H}" fill="white"/><text x="18" y="24" font-size="15" font-weight="600" fill="#234c40">${esc(title)}</text>`;
 for(let i=0;i<5;i++){const y=ymin+(ymax-ymin)*i/4;s+=`<line x1="${L}" x2="${R}" y1="${yy(y)}" y2="${yy(y)}" stroke="#e7ede7"/><text x="${L-8}" y="${yy(y)+4}" text-anchor="end" font-size="10" fill="#77897e">${esc(Number(y.toPrecision(4)))}</text>`;}
 for(let i=0;i<5;i++){const x=xmin+(xmax-xmin)*i/4,label=dateAxis?new Date(x).toISOString().slice(0,10):Number(x.toPrecision(4));s+=`<text x="${xx(x)}" y="${B+19}" text-anchor="middle" font-size="10" fill="#77897e">${esc(label)}</text>`;}
 if(band){let segment=[];const flush=()=>{if(segment.length>1)s+=`<polygon points="${segment.map(p=>`${xx(p.x)},${yy(p[band[0]])}`).concat([...segment].reverse().map(p=>`${xx(p.x)},${yy(p[band[1]])}`)).join(' ')}" fill="#c2dac8" opacity=".55"/>`;segment=[];};for(const p of valid){if(Number.isFinite(p[band[0]])&&Number.isFinite(p[band[1]]))segment.push(p);else flush();}flush();}
 series.forEach((line,j)=>{let seg=[];let prev=null;const flush=()=>{if(seg.length>1)s+=`<polyline points="${seg.join(' ')}" fill="none" stroke="${line.color}" stroke-width="${line.width||1.8}" ${line.dash?'stroke-dasharray="6 4"':''}/>`;else if(seg.length)s+=`<circle cx="${seg[0].split(',')[0]}" cy="${seg[0].split(',')[1]}" r="2.5" fill="${line.color}"/>`;seg=[];};for(const p of valid){if(!Number.isFinite(p[line.key])||(prev!==null&&dateAxis&&p.x-prev>86400000))flush();if(Number.isFinite(p[line.key]))seg.push(`${xx(p.x).toFixed(2)},${yy(p[line.key]).toFixed(2)}`);prev=p.x;}flush();s+=`<line x1="${L+j*175}" x2="${L+22+j*175}" y1="266" y2="266" stroke="${line.color}" stroke-width="2"/><text x="${L+28+j*175}" y="270" font-size="10" fill="#677f70">${esc(line.name)}</text>`;});
 s+=`<text x="${R}" y="${B+36}" text-anchor="end" font-size="10" fill="#77897e">${esc(xlabel)}</text><text x="${L}" y="${T-9}" font-size="10" fill="#77897e">${esc(ylabel)}</text></svg>`;return s;
}

window.loadResearch=async()=>{
 researchState=await api('/api/research');const s=researchState.summary;
 $('diagnosisStats').innerHTML=[['正常参考范围内',s.status_counts['正常参考范围内']||0],['持续异常',s.status_counts['持续异常']||0],['正常 / 异常模板',`${s.normal_templates} / ${s.abnormal_templates}`],['人工核定正常段',s.verified_normal_samples]].map(([k,v])=>`<div><label>${k}</label><strong>${v}</strong></div>`).join('');
 $('diagnosisFilter').innerHTML='<option value="">全部诊断状态</option>'+Object.keys(s.status_counts).map(k=>`<option>${esc(k)}</option>`).join('');
 $('projectAudit').textContent=researchState.project_audit.priority_wells?'项目资料核查：100口重点井；措施日报实际26个井号，其中16口重合。64口有压恢记录，9口有投产后测试；原资料无统一病因标签。':'当前为自导入数据：不自动关联项目井史。可自行核定样本并补充压力资料。';
 const options=state.features.map(f=>`<option value="${esc(f.well)}">${esc(f.well)}</option>`).join('');$('evidenceWell').innerHTML=options;$('labelWell').innerHTML=options;$('labelKind').innerHTML=researchState.kinds.map(k=>`<option>${esc(k)}</option>`).join('');
 renderDiagnosis();renderTemplateList();renderManualLabels();renderExtendedFeatures();renderMethods();
};

function renderDiagnosis(){if(!researchState)return;const query=$('diagnosisSearch').value.toLowerCase(),status=$('diagnosisFilter').value;const rows=researchState.rows.filter(r=>(!status||r.status===status)&&(!query||(r.well+' '+r.mechanism).toLowerCase().includes(query))).sort((a,b)=>(b.scores.loss_pct||0)-(a.scores.loss_pct||0));
 $('diagnosisTable').innerHTML=table(['井号 / 分组','分析时段','异常状态','候选原因','产气偏离损失','最大联合 Z','连续低产','证据'],rows.map(r=>[`<button data-well="${esc(r.well)}">${esc(r.well)}</button><small class="cellsub">${esc(r.group)}</small>`,`${r.start}<br>${r.end}`,rbadge(r.status),`${rbadge(r.mechanism)}<small class="cellsub">${esc(r.confidence)}</small>`,fmt(r.scores.loss_pct,1)+'%',fmt(r.scores.joint_z),fmt(r.scores.max_low_run,0)+' 天',`<button data-evidence-well="${esc(r.well)}">${r.evidence_count} 条历史依据</button>`]));
}
function renderExtendedFeatures(){let box=$('extendedFeatureExports');if(!box){box=document.createElement('div');box.id='extendedFeatureExports';$('featuresView').prepend(box);}box.innerHTML=`<div class="sectionbar"><div><p class="eyebrow">MULTISCALE MORPHOLOGY</p><h2>产量、压力、气水关系：多窗口与全历史分段</h2><p class="muted">30 / 90 / 180日及当前设置窗口，全部自动提取。单井曲线页可查看每一项参数和变化点。</p></div></div><div class="export-strip"><a href="/api/research/export/windows.csv">↓ 多窗口特征 CSV</a><a href="/api/research/export/segments.csv">↓ 全历史分段特征 CSV</a><a href="/api/research/export/changes.csv">↓ 变化点及前后参数 CSV</a></div><div class="notice">变化点来自14日中位序列的多通道分段回归；标注约±14日定位精度。负递减率表示回升，历史变化点不等同实时预警；最多显示8个候选点，达到上限不代表历史仅有8次变化。</div><div class="toolbar"><label>曲线通道 <select id="batchChannel">${Object.entries(channelNames).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>分析窗口 <select id="batchWindow">${[...new Set([30,90,180,state.settings.window])].sort((a,b)=>a-b).map(n=>`<option value="${n}" ${n===state.settings.window?'selected':''}>近${n}日</option>`).join('')}</select></label></div><div id="morphologyBatch" class="tablewrap"></div>`;$('batchChannel').addEventListener('change',renderMorphologyBatch);$('batchWindow').addEventListener('change',renderMorphologyBatch);renderMorphologyBatch();}

function renderMorphologyBatch(){const key=$('batchChannel').value,days=Number($('batchWindow').value);$('morphologyBatch').innerHTML=table(['井号','有效点','月等效递减','90日等效递减','残差CV','P90−P10幅度','相对幅度','前后变化','历史变化点'],researchState.rows.map(r=>{const m=(r.morphology||[]).find(m=>m.window===days),f=m?.channels[key]||{};return [`<button data-well="${esc(r.well)}">${esc(r.well)}</button>`,f.n??'—',fmt(f.d30,1)+'%',fmt(f.d90,1)+'%',fmt(f.cv),fmt(f.amplitude)+' '+channelUnits[key],fmt(f.amplitude_pct,1)+'%',fmt(f.change_pct,1)+'%',r.change_count];}));}

window.loadWellResearch=async w=>{
 const token=++researchSequence;$('evidenceContent').innerHTML=empty('正在读取本井证据…');$('wellResearch').innerHTML='<p class="muted">正在读取多通道特征与模板对照…</p>';
 const data=await api('/api/research/well?id='+encodeURIComponent(w));if(token!==researchSequence||selected!==w)return;researchWell=data;
 $('evidenceWell').value=w;$('labelWell').value=w;updateLabelDates();renderWellResearch();renderEvidence();
};
function renderWellResearch(){const d=researchWell,g=d.diagnosis,z=g.scores||{},wm=d.windows.find(m=>m.window===state.settings.window)||d.windows[1];
 $('wellResearch').innerHTML=`<div class="sectionbar"><div><p class="eyebrow">MORPHOLOGY → TEMPLATE → DIAGNOSIS</p><h2>本井形态特征与异常诊断</h2><p class="muted">${g.start} — ${g.end} · ${esc(g.basis)}</p></div>${rbadge(g.status)}</div><div class="diagnosis-banner"><div><small>当前候选结论</small><strong>${esc(g.mechanism)}</strong><span>${esc(g.confidence)}</span></div><div><small>相对基准产气偏离损失</small><strong>${fmt(z.loss_pct,1)}<em>%</em></strong></div><div><small>多通道最大标准化偏离</small><strong>${fmt(z.joint_z)}<em>Z</em></strong></div><div><small>连续低于预期70%</small><strong>${fmt(z.max_low_run,0)}<em>天</em></strong></div></div>${listText(g.reasons)}<div class="notice compact">${esc((g.limits||[]).join(' '))}</div>
 <div class="subsection"><div class="sectionbar"><h3>形态参数 · 六类曲线</h3><label>时间窗 <select id="featureWindow">${d.windows.map(m=>`<option value="${m.window}" ${m.window===wm.window?'selected':''}>近 ${m.window} 日</option>`).join('')}</select></label></div><div id="windowMetrics" class="tablewrap"></div></div>
 <details class="subsection"><summary>全历史变化点与生产阶段 · ${d.changes.length} 个变化点 / ${d.segments.length} 个阶段</summary><p class="muted">变化点是水平或斜率改变的候选日期；结合井史判断原因。</p><div class="tablewrap">${table(['候选日期','气量变化','气量递减：前 → 后','油压变化','套压变化','水气比变化'],d.changes.map(c=>[c.date+' ±14日',fmt(c.channels.gas.change_pct,1)+'%',fmt(c.channels.gas.before_d30,1)+'% → '+fmt(c.channels.gas.after_d30,1)+'%',fmt(c.channels.tubing.change_pct,1)+'%',fmt(c.channels.casing.change_pct,1)+'%',fmt(c.channels.wgr.change_pct,1)+'%']))}</div><div class="tablewrap">${table(['阶段','时间','气量月等效递减','油压斜率','套压斜率','产气残差CV','零产比例'],d.segments.map((s,i)=>[i+1,s.start+' — '+s.end,fmt(s.channels.gas.d30,1)+'%',fmt(s.channels.tubing.slope30)+' MPa/30d',fmt(s.channels.casing.slope30)+' MPa/30d',fmt(s.channels.gas.cv),fmt((s.zero_ratio||0)*100,1)+'%']))}</div></details>
 <section class="subsection"><div class="sectionbar"><div><h3>实际曲线与正常预期对照</h3><p class="muted">${g.normal_reference?`参考段：${g.normal_reference.start} — ${g.normal_reference.end} · ${g.normal_reference.verified?'人工核定':'规则筛选候选'} · 同组其他参考井 ${g.peer_count||0} 口`:'没有可用的历史正常参考段，请在样本与证据中核定。'}</p></div><button data-download-chart="normalOverlay">↓ SVG</button></div><div id="normalOverlay"></div><details><summary>压力与水气比的联合响应</summary><div id="pressureOverlay"></div><div id="waterOverlay"></div></details></section>
 <details class="subsection"><summary>异常模板相似性与诊断指标明细</summary><p class="muted">距离越小代表形态越接近，不代表病因概率。阈值为研究初筛配置，尚未独立校准。</p><div class="tablewrap">${table(['模板','分组','形态距离','有效通道','样本数'],(g.template_matches||[]).map(m=>[`<button data-template="${esc(m.id)}">${esc(m.label)}</button>`,esc(m.group),fmt(m.distance),m.channels,m.sample_count]))}</div><div class="tablewrap">${table(['通道','实际/正常预期','偏离幅度','标准化Z','有效天数'],(z.factors||[]).map(f=>[esc(f.name),fmt(f.ratio),fmt(f.deviation_pct,1)+'%',fmt(f.z),f.n]))}</div></details>
 <section class="subsection"><div class="sectionbar"><div><h3>q/Δp–Gp · 压力归一化产能</h3><p class="muted">Δp = 地层压力 − 井底流压；${d.pressure.n} 个有效点。油套压差不参与此计算。</p></div><button data-download-chart="productivityChart">↓ SVG</button></div><div id="productivityChart"></div><details><summary>补充本井压力资料 / 确认产气计量口径</summary><p class="muted">可在Excel中导入“地层压力、井底流压、累计产气”日列。也可为有依据的短时段录入恒压估算，界面将保留来源标记。压力必须使用相同基准。</p><div class="formrow"><label>有效起日<input id="pressureStart" type="date" value="${g.start}"></label><label>有效末日<input id="pressureEnd" type="date" value="${g.end}"></label><label>地层压力 / MPa<input id="reservoirInput" type="number" min="0" max="200" step=".01" placeholder="不填则仅更新计量口径"></label><label>井底流压 / MPa<input id="flowingInput" type="number" min="0" max="200" step=".01"></label></div><div class="formrow pressure-row"><label>日报产气含义<select id="volumeMode"><option value="unknown">未确认；只用导入的累计气量</option><option value="daily_volume">每日实际产气量；按日累加</option><option value="rate">24小时折算日产率；乘生产小时/24</option></select></label><label>测试 / 估算来源<input id="pressureSource" placeholder="资料名称、测试日期或估算依据"></label></div><button id="savePressure" class="primary">保存资料并更新量压曲线</button><p class="smallnote">不填写压力将清除本井旧的区间压力，保留原始导入日列。缺日不补零；横轴未自动补齐日报开始前的累计气量。</p><div id="pressureHistory"></div></details></section>
 <div class="toolbar"><button data-evidence-well="${esc(selected)}">查看本井井史与证据</button><a href="/api/research/export/windows.csv">导出全部井多窗口特征</a></div>`;
 renderWindow(wm.window);$('featureWindow').addEventListener('change',()=>renderWindow(Number($('featureWindow').value)));
 const overlay=(g.overlay||[]).map(p=>({...p,x:Date.parse(p.date)}));
 $('normalOverlay').innerHTML=overlay.length?researchChart({title:selected+' · 产气与正常预期',points:overlay,dateAxis:true,series:[{key:'gas_actual',name:'实际日产气',color:'#bd7947'},{key:'gas',name:'正常预期',color:'#26795e',dash:true}],band:['gas_low','gas_high'],ylabel:'m³/d',xlabel:'日期；浅色为历史残差经验范围'}):empty('缺少独立的历史正常参考段，未生成外推曲线。');
 $('pressureOverlay').innerHTML=overlay.length?researchChart({title:'油压与套压：实际 / 正常预期',points:overlay,dateAxis:true,series:[{key:'tubing_actual',name:'实际油压',color:'#c8903b'},{key:'tubing',name:'预期油压',color:'#c8903b',dash:true},{key:'casing_actual',name:'实际套压',color:'#537faa'},{key:'casing',name:'预期套压',color:'#537faa',dash:true}],ylabel:'MPa'}):'';
 $('waterOverlay').innerHTML=overlay.length?researchChart({title:'水气比：实际 / 正常预期',points:overlay,dateAxis:true,series:[{key:'wgr_actual',name:'实际水气比',color:'#976fa2'},{key:'wgr',name:'预期水气比',color:'#26795e',dash:true}],ylabel:'m³水/万m³气'}):'';
 $('productivityChart').innerHTML=d.pressure.n?researchChart({title:selected+' · q/Δp–Gp',points:d.pressure.points.map(p=>({...p,x:p.gp})),series:[{key:'j',name:'q/(pr−pwf)',color:'#26795e'}],xlabel:'累计气量 / m³（口径见来源）',ylabel:'m³/(d·MPa)'})+`<p class="smallnote">${esc(d.pressure.x_label)}。${d.pressure.gaps?'存在缺日或缺值，观测期累产不完整。':''} 压力来源：${esc([...new Set(d.pressure.points.map(p=>p.source))].join('；'))}</p>`:empty(d.pressure.reason);
 $('volumeMode').value=d.pressure.volume_mode;$('pressureHistory').innerHTML=listText((d.pressure.intervals||[]).map(i=>`${i.start} — ${i.end}：pr=${i.reservoir}，pwf=${i.flowing} MPa；${i.source}`));
 $('savePressure').addEventListener('click',act(async()=>{await api('/api/research/pressure',{well:selected,start:$('pressureStart').value,end:$('pressureEnd').value,reservoir:$('reservoirInput').value,flowing:$('flowingInput').value,source:$('pressureSource').value,volume_mode:$('volumeMode').value});await watchJob();toast('本井压力资料和量压曲线已更新。');}));
}
function renderWindow(days){const m=researchWell.windows.find(m=>m.window===days);$('windowMetrics').innerHTML=table(['曲线','有效点','月等效递减','90日等效递减','线性斜率/30日','残差CV','P90−P10幅度','相对幅度','前后变化'],Object.entries(m.channels).map(([k,c])=>[channelNames[k],c.n,fmt(c.d30,1)+'%',fmt(c.d90,1)+'%',fmt(c.slope30)+' '+channelUnits[k],fmt(c.cv),fmt(c.amplitude)+' '+channelUnits[k],fmt(c.amplitude_pct,1)+'%',fmt(c.change_pct,1)+'%']))+`<p class="smallnote">${m.start} — ${m.end}；覆盖率 ${fmt(m.coverage*100,1)}%；零产 ${fmt((m.zero_ratio||0)*100,1)}%。产气趋势按生产时数筛选；比值缺失与零值保留区分。压力/水量对数趋势只是描述性特征。</p>`;}

function renderTemplateList(){if(!researchState)return;const filter=$('templateFilter').value,items=researchState.templates.filter(t=>!filter||t.label===filter).sort((a,b)=>(b.label==='正常')-(a.label==='正常')||b.sample_count-a.sample_count);if(!items.some(t=>t.id===templateId))templateId=items[0]?.id;
 $('templateList').innerHTML=items.map(t=>`<button class="template-item ${t.id===templateId?'active':''}" data-template="${esc(t.id)}"><b>${esc(t.label)} · ${esc(t.group)}</b><small>${t.well_count} 口井 / ${t.sample_count} 个时段</small>${rbadge(t.verified_count===t.sample_count?'人工核定':'候选参考')}</button>`).join('')||empty('尚无这一类型的合格样本，可在“样本与证据”中核定时段。');renderTemplate();}
function renderTemplate(){const t=researchState?.templates.find(t=>t.id===templateId);if(!t){$('templateDetail').innerHTML=empty('请先核定生产时段以建立模板。');return;}
 const chart=(key,title)=>researchChart({title,points:t.curves[key],series:[{key:'median',name:'样本中位形态',color:'#28745b'}],band:['low','high'],xlabel:'相对生产阶段 0 → 1',ylabel:'相对本段前20%中位值'});
 $('templateDetail').innerHTML=`<div class="sectionbar"><div><h2>${esc(t.label)}模板 · ${esc(t.group)}</h2><p class="muted">${t.sample_count} 个时段，${t.well_count} 口井，${t.verified_count} 个已人工核定。代表井：${esc(t.representative.well)}</p></div><button data-download-chart="templateCharts">↓ 模板 SVG</button></div><div class="notice">${esc(t.status)}。${esc(t.warning)}</div><div id="templateCharts">${chart('gas','产量—相对时间模板')}${chart('tubing','油压—相对时间模板')}${chart('casing','套压—相对时间模板')}${chart('water','产水—相对时间模板')}${chart('wgr','水气比—相对时间模板')}${chart('gwr','气水比—相对时间模板')}</div><h3>q/Δp–Gp模板</h3>${t.pressure_productivity.available?researchChart({title:'压力归一化产能—累产模板',points:t.pressure_productivity.curve,series:[{key:'median',name:'样本中位形态',color:'#28745b'}],band:['low','high'],xlabel:'本段相对累计气量',ylabel:'相对q/Δp'}):empty(t.pressure_productivity.reason)}<h3>模板样本与判定依据</h3><div class="tablewrap">${table(['井号','生产时段','样本来源','核定状态','依据'],t.samples.map(s=>[`<button data-well="${esc(s.well)}">${esc(s.well)}</button>`,s.start+' — '+s.end,esc(s.origin),s.verified?'人工核定':'候选 / 待核',`<span class="wrapcell">${esc(s.reason)}</span>`]))}</div>`;
}
function renderEvidence(){if(!researchWell)return;const d=researchWell;$('evidenceContent').innerHTML=`<div class="evidence-grid">${d.evidence.map(e=>`<article class="evidence-card"><div>${rbadge(e.label)} ${rbadge(e.level)}</div><h3>${esc(e.title)}</h3><small>${e.start} — ${e.end}</small><p>${esc(e.detail)}</p><p class="smallnote">${esc(e.locator)} · ${esc(e.origin)}</p>${e.origin==='项目文件'?`<a class="source-local">资料已在本地归档</a>`:''}<details><summary>来源路径</summary><p class="pathtext">${esc(e.source)}</p></details></article>`).join('')||empty('此井尚无已整理的病因证据；没有证据不等于正常。可继续核定生产时段。')}</div><details class="subsection"><summary>已关联措施记录 · ${d.events.length} 条</summary><div class="tablewrap">${table(['日期','措施/说明','统计表原行号'],d.events.map(e=>[esc(e.date),esc(e.note),e.row]))}</div></details><details class="subsection"><summary>压恢试井资料 · ${d.pressure_tests.length} 条</summary><p class="muted">外推地层压力仅对应测试时点；早期试气不能直接替代当前压力。表皮值不能单独区分堵塞与水锁。</p><div class="tablewrap">${table(['测试起日','测试阶段','地层压力 / MPa','表皮系数','原表行号'],d.pressure_tests.map(t=>[esc(t.date.slice(0,10)),esc(t.stage),esc(t.pr??'—'),esc(t.skin??'—'),t.row]))}</div></details>`;}
function updateLabelDates(){const f=state?.features.find(f=>f.well===$('labelWell').value);if(!f)return;$('labelStart').value=f.start;$('labelEnd').value=f.end;}
function renderManualLabels(){$('manualLabels').innerHTML='<h3>已保存的人工时段</h3>'+table(['井号','时段','类型','依据','操作'],researchState.labels.map(e=>[esc(e.well),e.start+' — '+e.end,esc(e.label),`<span class="wrapcell">${esc(e.detail)}</span>`,`<button data-delete-label="${esc(e.id)}">移除标签</button>`]));}

function renderMethods(){$('methodsContent').innerHTML=`<p class="eyebrow">SCIENTIFIC BASIS / YANBEI</p><h2>延北低压致密气井：模板偏离与多证据诊断</h2><p class="method-lead">工况分段 → 多通道特征 → 本井历史与同类井基准 → 异常偏离 → 病因证据复核。当前为可解释的研究筛查模型，尚未完成独立现场精度验证。</p><div class="method-grid"><article><h3>01　形态特征与变化点</h3><p>30/90/180日窗口及全历史生产段，提取气量、油压、套压、产水、水气比、气水比。稳健对数趋势得到D30 = 100×[1−exp(30b)]；MAD剔除极端拟合残差。波动同时给出残差CV与P90−P10幅度。</p><p>变化点：14日中位序列，气量与压力、水气比标准化后做带惩罚的二分分段回归。此处采用可解释的分段方法，并未宣称实现PELT或实时预警。</p></article><article><h3>02　正常参考与双基准</h3><p>自动候选段至少60条、覆盖≥85%、零产≤5%、充分生产时数≥80%、CV≤0.25；排除已知伤害与措施相邻段。分析窗全部留出，不参与本井基准拟合。</p><p>有至少3口同层位/井型其他参考井时，用本井趋势65%＋同组中位趋势35%修正外推；不足则使用本井历史。权重与筛选阈值为待标定配置。人工正常标签可以替代自动候选。</p></article><article><h3>03　定量偏离与机制分层</h3><p>产气偏离损失=100×max[0,1−median(q/q正常)]；每个通道用对数残差与历史MAD尺度计算Z，联合分数取最大绝对Z。参考范围由历史残差构建，不冒充已经校准的预测区间。</p><p>初筛：产气损失≥30%且气量Z≥3且连续低于正常70%至少7日；或联合Z≥5；或零产≥20%。模板相似性用归一化阶段曲线对数均方距离，只表示形态相近。病因优先结合相同时段证据。</p></article><article><h3>04　量压曲线与数据条件</h3><p>q/Δp使用地层压力pr与井底流压pwf；不使用油套压差。支持逐日压力列、Gp列及明确来源的区间恒压估算。小压差≤0.05 MPa不计算，防止比值不稳定。</p><p>未确认日气量口径不自动累产。实测日气量直接累加，折算日产率按时数积分。未补齐投产前历史时标为观测期累计气量。气体拟压力和严格两相RTA需要PVT/相渗，当前未伪装实现。</p></article></div><div class="notice">创新研究方向：同类井与自身历史联合基准、积液/堵塞/水锁证据分层、低压资料条件控制。需通过按井分组验证、事件回放、误报漏报与消融对比证明，不将模型组合直接宣称为已验证创新。</div><h3>参考文献与本软件的对应关系</h3><div class="tablewrap">${table(['文献','借鉴内容','使用边界'],[
['<a target="_blank" rel="noopener" href="https://doi.org/10.1016/j.petrol.2022.110522">Chen等，2022 · JPSE ↗</a>','正常行为学习、残差与自适应异常识别','原文是积液诊断；本软件使用透明残差基线，没有复现其神经网络'],
['<a target="_blank" rel="noopener" href="https://doi.org/10.1016/j.geoen.2023.212254">Wang等，2023 · Geoenergy Science and Engineering ↗</a>','气水两相量压关系与拟压力RTA','需PVT、相渗和井底压力；当前q/Δp为描述性产能指标'],
['<a target="_blank" rel="noopener" href="https://doi.org/10.2118/223596-PA">Han等，2024 · SPE Journal ↗</a>','多井共享信息＋单井历史、预测区间','借鉴双层参考思想；未复现DeepAR'],
['<a target="_blank" rel="noopener" href="https://doi.org/10.1021/acsomega.4c03957">Sun等，2024 · ACS Omega ↗</a>','临兴致密气井量压耦合、积液与排液响应','井筒积液不是储层水锁'],
['<a target="_blank" rel="noopener" href="https://doi.org/10.1016/j.petrol.2022.111152">Tian等，2023 · JPSE ↗</a>','返排、水相滞留及储层伤害机理','岩心实验不能替代单井确诊'],
['<a target="_blank" rel="noopener" href="https://doi.org/10.13639/j.odpt.202504028">郭亚非等，2025 · 石油钻采工艺 ↗</a>','多维积液诊断与动态跟踪','外区块阈值不得直接照搬'],
['<a target="_blank" rel="noopener" href="https://doi.org/10.1016/j.eswa.2026.131580">Zeng等，2026 · Expert Systems with Applications ↗</a>','积液严重程度分级与对比学习方向','仅作后续比较方向，当前未训练深度模型']])}</div><p class="muted">文献经出版社/期刊网页与元数据核验；部分只取得摘要/预览，未宣称已完成WoS或知网订阅系统全文检索。详见项目研究方法说明。</p>`;}

$('diagnosisSearch').addEventListener('input',renderDiagnosis);$('diagnosisFilter').addEventListener('change',renderDiagnosis);$('templateFilter').addEventListener('change',renderTemplateList);$('labelWell').addEventListener('change',updateLabelDates);
$('evidenceWell').addEventListener('change',act(async()=>{await selectWell($('evidenceWell').value);showView('evidence');}));
$('rebuildResearch').addEventListener('click',act(async()=>{await api('/api/research/rebuild',{});await watchJob();toast('模板与逐井诊断已更新。');}));
$('addResearchLabel').addEventListener('click',act(async()=>{await api('/api/research/label',{well:$('labelWell').value,start:$('labelStart').value,end:$('labelEnd').value,label:$('labelKind').value,detail:$('labelDetail').value});$('labelDetail').value='';await watchJob();toast('人工时段已保存并纳入模板。');}));
document.addEventListener('click',act(async e=>{const t=e.target.closest('[data-template]');if(t){templateId=t.dataset.template;$('templateFilter').value='';renderTemplateList();showView('templates');}const b=e.target.closest('[data-evidence-well]');if(b){await selectWell(b.dataset.evidenceWell);showView('evidence');}const del=e.target.closest('[data-delete-label]');if(del){await api('/api/research/label/delete',{id:del.dataset.deleteLabel});await watchJob();toast('标签已移除，原始数据保留。');}const save=e.target.closest('[data-download-chart]');if(save){const svgs=[...$(save.dataset.downloadChart).querySelectorAll('svg')];if(!svgs.length)throw Error('此图缺少必要数据，尚未生成。');svgs.forEach((svg,i)=>download(new Blob([svg.outerHTML],{type:'image/svg+xml'}),`${selected||'template'}_${save.dataset.downloadChart}_${i+1}.svg`));}}));
